name: CI

on:
  pull_request:

jobs:
  ci:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - project-template-esp32-release.yaml
          - project-template-esp32-c3-release.yaml
          - project-template-esp32-s3-release.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.7
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v3.2.0
        with:
          yaml_file: ${{ matrix.file }}
